"""PR18: Independent Production Oracle and Semantic Evidence Validation Tests.

Covers:
  L0 — Unit semantic tests (self-referential, oracle compare, exit diff)
  L1 — Property and invariant tests (single-industry constraint, evidence semantics)
  L2 — Independent P0/C0 Golden regression (no-DB smoke test)
  L3 — Anti-future-function mutation tests
  L4 — Evidence semantic gate tests (empty NAV, NOT_FITTED, source_complete)
"""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pandas as pd
import pytest

# Ensure project root on path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
import sys
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ============================================================================
# L0: Self-Referential Detection Tests
# ============================================================================


class TestSelfReferentialDetection:
    """Detect self-referential oracles (adapter vs wrapped-adapter)."""

    def test_detect_same_class(self):
        """Same class name should trigger self-referential detection."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            OracleProvenance,
            OracleSource,
            detect_self_referential,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="scripts.research.strategy_adapters.ProductionStrategyAdapter",
                generating_function="ProductionStrategyAdapter.rank",
            ),
        )

        result = detect_self_referential(
            oracle,
            "ProductionStrategyAdapter",
            "rank",
        )
        assert result["is_self_referential"]
        assert "SELF_REFERENTIAL_ORACLE" in result["reason"]

    def test_detect_adapter_runtime_generated(self):
        """Oracle generated by AdapterRuntime should be flagged."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            OracleProvenance,
            OracleSource,
            detect_self_referential,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="AdapterRuntime",
                generating_function="AdapterRuntime.rank_as_of",
            ),
        )

        result = detect_self_referential(oracle, "FrozenAlphaRuntime", "rank_as_of")
        assert result["is_self_referential"]

    def test_detect_adapter_method_generated(self):
        """Oracle generated by 'rank' method should be flagged."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            OracleProvenance,
            OracleSource,
            detect_self_referential,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="C0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="SomeExternalClass",
                generating_function="SomeExternalClass.build_weights",
            ),
        )

        result = detect_self_referential(oracle, "DifferentClass", "transform")
        # build_weights is an adapter method → should be flagged
        assert result["is_self_referential"]

    def test_independent_oracle_passes(self):
        """Oracle from independent source should NOT be flagged."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            OracleProvenance,
            OracleSource,
            detect_self_referential,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.PRODUCTION_DB_EXPORT,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="production_scheduler.export_daily_decisions",
                generating_function="production_scheduler.export_daily_decisions.run",
            ),
        )

        result = detect_self_referential(oracle, "FrozenAlphaRuntime", "rank_as_of")
        assert not result["is_self_referential"]


# ============================================================================
# L0: Frozen Oracle Export/Load Tests
# ============================================================================


class TestFrozenOracleIO:
    """Test frozen oracle export and loading."""

    def test_export_and_load_roundtrip(self, tmp_path):
        """Export oracle decisions and load them back."""
        from scripts.research.frozen_oracle import (
            export_frozen_oracle,
            load_frozen_oracle_from_file,
        )

        decisions = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["000001", "000002", "000003", "000004", "000005"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.18, 0.16, 0.14, 0.12, 0.10],
            }),
            "2026-01-03": pd.DataFrame({
                "symbol": ["000002", "000003", "000001", "000005", "000006"],
                "rank_score": [92.0, 88.0, 86.0, 82.0, 78.0],
                "final_portfolio_weight": [0.17, 0.16, 0.15, 0.12, 0.10],
            }),
        }

        oracle_dir = tmp_path / "test_oracle"
        oracle = export_frozen_oracle(
            decisions=decisions,
            strategy_id="test_strategy",
            experiment_id="P0",
            git_commit_sha="abc123",
            generating_class="tests.test_pr18_independent_oracle",
            generating_function="test_export_and_load_roundtrip",
            output_dir=oracle_dir,
        )

        assert oracle.n_dates == 2
        assert oracle.date_range[0] == "2026-01-02"
        assert (oracle_dir / "provenance.json").is_file()
        assert (oracle_dir / "decisions.parquet").is_file()

        # Load back
        loaded = load_frozen_oracle_from_file(oracle_dir)
        assert loaded.n_dates == 2
        assert loaded.get_decision("2026-01-02") is not None
        decision = loaded.get_decision("2026-01-02")
        assert decision.symbols == ("000001", "000002", "000003", "000004", "000005")
        assert abs(decision.total_exposure - 0.70) < 0.01

    def test_load_missing_provenance_fails(self, tmp_path):
        """Loading oracle without provenance should fail."""
        from scripts.research.frozen_oracle import load_frozen_oracle_from_file

        oracle_dir = tmp_path / "bad_oracle"
        oracle_dir.mkdir()
        # No provenance.json

        with pytest.raises(FileNotFoundError):
            load_frozen_oracle_from_file(oracle_dir)


# ============================================================================
# L0: Oracle Comparison Tests (including exit diffs)
# ============================================================================


class TestOracleComparison:
    """Test oracle comparison including real exit diffs."""

    def test_exact_match_passes(self):
        """Runtime output matching oracle exactly should pass."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B", "C", "D", "E"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                ),
            },
        )

        runtime_outputs = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["A", "B", "C", "D", "E"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.18, 0.16, 0.14, 0.12, 0.10],
            }),
        }

        result = compare_against_oracle(
            oracle, runtime_outputs, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert result.passed
        assert not result.is_self_referential
        assert result.candidate_diff_max == 0

    def test_different_candidates_fails(self):
        """Different candidates should fail the comparison."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B", "C", "D", "E"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                ),
            },
        )

        # Different symbols
        runtime_outputs = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["X", "Y", "Z", "A", "B"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.18, 0.16, 0.14, 0.12, 0.10],
            }),
        }

        result = compare_against_oracle(
            oracle, runtime_outputs, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.candidate_diff_max > 0

    def test_different_weights_fails(self):
        """Different weights should fail the comparison."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B", "C", "D", "E"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                ),
            },
        )

        # Same symbols but different weights
        runtime_outputs = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["A", "B", "C", "D", "E"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.30, 0.20, 0.10, 0.05, 0.05],  # different
            }),
        }

        result = compare_against_oracle(
            oracle, runtime_outputs, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.weight_diff_max > 0.10  # significant difference

    def test_exit_diff_detected(self):
        """Real exit differences should be detected (not hardcoded 0)."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-10": FrozenDailyDecision(
                    signal_date="2026-01-10",
                    symbols=("A", "B"),
                    rank_scores=(95.0, 90.0),
                    final_weights=(0.35, 0.35),
                    total_exposure=0.70,
                    exit_decisions=(
                        {"symbol": "A", "exit_date": "2026-01-10", "exit_reason": "TIME_STOP", "exit_shares": "1000"},
                    ),
                ),
            },
        )

        # Runtime has different exit reason
        runtime_outputs = {
            "2026-01-10": pd.DataFrame({
                "symbol": ["A", "B"],
                "rank_score": [95.0, 90.0],
                "final_portfolio_weight": [0.35, 0.35],
                "exit_symbol": ["A", ""],
                "exit_date": ["2026-01-10", ""],
                "exit_reason": ["HARD_STOP", ""],  # different reason!
                "exit_shares": ["1000", ""],
            }),
        }

        result = compare_against_oracle(
            oracle, runtime_outputs, top_n=2,
            test_class_name="FrozenAlphaRuntime",
        )
        # Exit reason mismatch should be detected
        assert result.exit_diff_count > 0

    def test_self_referential_fails_immediately(self):
        """Self-referential oracle should fail without comparing data."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="scripts.research.strategy_adapters.ProductionStrategyAdapter",
                generating_function="ProductionStrategyAdapter.rank",
            ),
        )

        result = compare_against_oracle(
            oracle, {},
            test_class_name="ProductionStrategyAdapter",
        )
        assert result.is_self_referential
        assert not result.passed


# ============================================================================
# L1: Single-Industry Constraint Test (PR19 bug fix preview)
# ============================================================================


class TestSingleIndustryConstraint:
    """Industry cap must be enforced even when all stocks are in one industry."""

    def test_single_industry_still_capped(self):
        """Top-5 all in semiconductors → industry cap at 30%, not 70%."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        raw = np.array([0.25, 0.20, 0.20, 0.18, 0.17])
        symbols = ["S1", "S2", "S3", "S4", "S5"]
        industries = ["半导体", "半导体", "半导体", "半导体", "半导体"]
        risk = np.array([0.3, 0.25, 0.25, 0.22, 0.20])

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            risk_values=risk,
            single_cap=0.15,
            industry_cap=0.30,
            target_gross_exposure=0.70,
        )

        # Industry total should be ≤ 0.30 even with single industry
        industry_total = result["final_portfolio_weight"].sum()
        assert industry_total <= 0.30 + 1e-6, (
            f"Single-industry constraint violated: {industry_total:.4f} > 0.30"
        )

    def test_multi_industry_enforced(self):
        """Multiple industries should have each industry capped."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        raw = np.array([0.25, 0.20, 0.20, 0.18, 0.17])
        symbols = ["S1", "S2", "S3", "S4", "S5"]
        industries = ["半导体", "半导体", "银行", "银行", "医药"]
        risk = np.array([0.3, 0.25, 0.25, 0.22, 0.20])

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            risk_values=risk,
            single_cap=0.15,
            industry_cap=0.30,
            target_gross_exposure=0.70,
        )

        for ind in set(industries):
            ind_total = result[result["industry"] == ind]["final_portfolio_weight"].sum()
            assert ind_total <= 0.30 + 1e-6, (
                f"Industry '{ind}' constraint violated: {ind_total:.4f} > 0.30"
            )

    def test_single_theme_still_capped(self):
        """Single theme should still enforce theme cap."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        raw = np.array([0.25, 0.20, 0.20, 0.18, 0.17])
        symbols = ["S1", "S2", "S3", "S4", "S5"]
        industries = ["半导体", "半导体", "银行", "银行", "医药"]
        themes = ["AI", "AI", "AI", "AI", "AI"]  # all same theme
        risk = np.array([0.3, 0.25, 0.25, 0.22, 0.20])

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            themes=themes,
            risk_values=risk,
            single_cap=0.15,
            industry_cap=0.30,
            theme_cap=0.40,
            target_gross_exposure=0.70,
        )

        theme_total = result["final_portfolio_weight"].sum()
        assert theme_total <= 0.40 + 1e-6, (
            f"Single-theme constraint violated: {theme_total:.4f} > 0.40"
        )

    def test_top2_risk_contribution_capped(self):
        """Top-2 risk contribution should be ≤ 45%."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        # Create highly concentrated risk scenario
        raw = np.array([0.30, 0.30, 0.15, 0.15, 0.10])
        symbols = ["S1", "S2", "S3", "S4", "S5"]
        industries = ["A", "B", "C", "D", "E"]
        risk = np.array([0.50, 0.45, 0.10, 0.10, 0.05])  # S1, S2 are very risky

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            risk_values=risk,
            single_cap=0.20,
            top2_risk_cap=0.45,
            target_gross_exposure=0.70,
        )

        # Top-2 risk contribution should be capped
        top2_risk = float(result["risk_contribution_pct"].nlargest(2).sum())
        assert top2_risk <= 0.45 + 1e-6, (
            f"Top-2 risk constraint violated: {top2_risk:.4f} > 0.45"
        )


# ============================================================================
# L4: Evidence Semantic Validation Tests
# ============================================================================


class TestEvidenceSemanticValidation:
    """Semantic evidence validation gates."""

    def _make_minimal_evidence_dir(self, tmp_path, **overrides):
        """Create a minimal evidence package directory for testing.

        PR20: Creates per-experiment subdirectories (P0/, C0/, A7/, A8/, A9/)
        since flat evidence packages are no longer accepted.
        """
        evidence_dir = tmp_path / "evidence"
        evidence_dir.mkdir()

        # Default: empty files
        defaults = {
            "manifest.json": json.dumps({
                "git_commit_sha": "abc123",
                "worktree_clean": True,
                "config_sha": "sha1",
                "data_sha": "sha2",
                "calendar_sha": "sha3",
                "corporate_action_sha": "sha4",
                "lifecycle_sha": "sha5",
                "python_version": "3.11",
                "dependency_lock_sha": "sha6",
                "evidence_status": "REPRODUCIBLE",
                "promotion_status": "PROMOTION_BLOCKED",
                "files": {},
            }),
            "factor_state_by_fold.json": json.dumps({
                "2025H1": {"status": "NOT_FITTED", "reason": "PR18_matrix_not_run"},
                "2025H2": {"status": "NOT_FITTED", "reason": "PR18_matrix_not_run"},
                "2026H1": {"status": "NOT_FITTED", "reason": "PR18_matrix_not_run"},
            }),
            "corporate_action_snapshot.json": json.dumps({
                "source": "ods_dividend",
                "summary": {"rows": 1000},
                "source_complete": False,
            }),
            "security_lifecycle_snapshot.json": json.dumps({
                "source": "dim_stock",
                "summary": {"rows": 5000},
                "source_complete": False,
            }),
        }

        for name, content in {**defaults, **overrides}.items():
            (evidence_dir / name).write_text(str(content), encoding="utf-8")

        # Create empty parquet files at root level
        for name in ["daily_nav.parquet", "trade_ledger.parquet",
                      "daily_candidates.parquet", "daily_weights.parquet",
                      "daily_exposure.parquet", "rejection_ledger.parquet"]:
            path = evidence_dir / name
            if not path.exists():
                pd.DataFrame().to_parquet(path)

        # PR20: Create per-experiment subdirectories with minimal data
        for exp_id in ["P0", "C0", "A7", "A8", "A9"]:
            exp_dir = evidence_dir / exp_id
            exp_dir.mkdir(exist_ok=True)
            for name in ["daily_nav.parquet", "trade_ledger.parquet",
                          "daily_candidates.parquet", "daily_weights.parquet"]:
                path = exp_dir / name
                if not path.exists():
                    pd.DataFrame().to_parquet(path)

        # Create empty CSV files
        for name in ["random_seed_results.csv", "walk_forward_metrics.csv",
                      "stitched_oos_nav.csv"]:
            path = evidence_dir / name
            if not path.exists():
                path.write_text("seed_id\n" + "\n".join(f"seed_{i}" for i in range(20)))

        # Create remaining required files
        for name in ["git_state.json", "config_snapshot.json", "data_snapshot.json",
                      "calendar_snapshot.json", "fold_definitions.json",
                      "test_log.txt"]:
            path = evidence_dir / name
            if not path.exists():
                path.write_text("{}")

        return evidence_dir

    def test_empty_nav_fails_semantic(self, tmp_path):
        """Empty daily_nav should fail semantic validation."""
        from scripts.research.evidence_semantic import validate_evidence_semantics, SemanticEvidenceStatus

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)
        # NAV is already empty (default)

        report = validate_evidence_semantics(evidence_dir)
        assert not report.passed
        # PR20: Empty per-exp dirs cause INSUFFICIENT_OOS_COVERAGE (checked before EMPTY)
        assert report.status in (
            SemanticEvidenceStatus.EMPTY_RESULTS.value,
            SemanticEvidenceStatus.NON_REPRODUCIBLE.value,
            SemanticEvidenceStatus.INSUFFICIENT_OOS_COVERAGE.value,
        )

    def test_empty_ledger_fails_semantic(self, tmp_path):
        """Empty trade_ledger should fail semantic validation."""
        from scripts.research.evidence_semantic import validate_evidence_semantics

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)

        # Add NAV with rows but keep ledger empty
        nav = pd.DataFrame({
            "trade_date": ["2026-01-02", "2026-01-03"],
            "nav": [1.0, 1.01],
        })
        nav.to_parquet(evidence_dir / "daily_nav.parquet")

        report = validate_evidence_semantics(evidence_dir)
        assert not report.passed
        assert any("ledger" in err.lower() or "empty" in err.lower()
                   for err in report.errors)

    def test_not_fitted_fails_semantic(self, tmp_path):
        """NOT_FITTED factor states should fail semantic validation."""
        from scripts.research.evidence_semantic import validate_evidence_semantics, SemanticEvidenceStatus

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)
        # factor_state_by_fold already has NOT_FITTED (default)

        # Add NAV data to get past EMPTY check (root + per-experiment)
        dates = pd.date_range("2025-01-02", periods=30, freq="B")
        nav = pd.DataFrame({"trade_date": dates, "nav": np.cumprod(1 + np.random.randn(30) * 0.01)})
        nav.to_parquet(evidence_dir / "daily_nav.parquet")
        # PR20: Also write to per-experiment directories
        for exp_id in ["P0", "C0", "A7", "A8", "A9"]:
            exp_dir = evidence_dir / exp_id
            nav.to_parquet(exp_dir / "daily_nav.parquet")

        # Add candidates
        candidates = pd.DataFrame({
            "trade_date": ["2026-01-02"],
            "symbol": ["000001"],
            "rank_score": [95.0],
        })
        candidates.to_parquet(evidence_dir / "daily_candidates.parquet")

        # Add weights
        weights = pd.DataFrame({
            "trade_date": ["2026-01-02"],
            "symbol": ["000001"],
            "final_portfolio_weight": [0.14],
        })
        weights.to_parquet(evidence_dir / "daily_weights.parquet")

        # Add ledger with trades
        ledger = pd.DataFrame({
            "trade_date": ["2026-01-02"],
            "symbol": ["000001"],
        })
        ledger.to_parquet(evidence_dir / "trade_ledger.parquet")

        # Add random seeds with results
        pd.DataFrame({
            "seed_id": [f"seed_{i}" for i in range(20)],
            "total_return": np.random.randn(20) * 0.1,
        }).to_csv(evidence_dir / "random_seed_results.csv", index=False)

        report = validate_evidence_semantics(evidence_dir)
        assert not report.passed
        assert report.status == SemanticEvidenceStatus.NOT_FITTED.value

    def test_source_incomplete_fails_semantic(self, tmp_path):
        """source_complete=False should fail semantic validation."""
        from scripts.research.evidence_semantic import validate_evidence_semantics, SemanticEvidenceStatus

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)

        # Fix factor states to FITTED
        (evidence_dir / "factor_state_by_fold.json").write_text(json.dumps({
            "2025H1": {"status": "FITTED"},
            "2025H2": {"status": "FITTED"},
            "2026H1": {"status": "FITTED"},
        }))

        # Add data to get past EMPTY check (root + per-experiment for PR20)
        dates = pd.date_range("2025-01-02", periods=30, freq="B")
        nav = pd.DataFrame({"trade_date": dates, "nav": np.cumprod(1 + np.random.randn(30) * 0.01)})
        nav.to_parquet(evidence_dir / "daily_nav.parquet")
        # PR20: Write to per-experiment directories too
        for exp_id in ["P0", "C0", "A7", "A8", "A9"]:
            nav.to_parquet((evidence_dir / exp_id) / "daily_nav.parquet")
        candidates = pd.DataFrame({"trade_date": ["2026-01-02"], "symbol": ["000001"]})
        candidates.to_parquet(evidence_dir / "daily_candidates.parquet")
        ledger = pd.DataFrame({"trade_date": ["2026-01-02"], "symbol": ["000001"]})
        ledger.to_parquet(evidence_dir / "trade_ledger.parquet")
        weights = pd.DataFrame({"trade_date": ["2026-01-02"], "symbol": ["000001"],
                                "final_portfolio_weight": [0.14]})
        weights.to_parquet(evidence_dir / "daily_weights.parquet")
        # random seeds with results
        pd.DataFrame({
            "seed_id": [f"seed_{i}" for i in range(20)],
            "total_return": np.random.randn(20) * 0.1,
        }).to_csv(evidence_dir / "random_seed_results.csv", index=False)

        # source_complete is still False (default)
        report = validate_evidence_semantics(evidence_dir)
        assert not report.passed
        assert report.status == SemanticEvidenceStatus.SOURCE_INCOMPLETE.value

    def test_all_valid_passes_semantic(self, tmp_path):
        """Fully valid evidence package should pass.

        PR20: Requires per-experiment directories with actual data across windows.
        """
        from scripts.research.evidence_semantic import validate_evidence_semantics, SemanticEvidenceStatus

        overrides = {
            "factor_state_by_fold.json": json.dumps({
                "2025H1": {"status": "FITTED"},
                "2025H2": {"status": "FITTED"},
                "2026H1": {"status": "FITTED"},
            }),
            "corporate_action_snapshot.json": json.dumps({
                "source": "ods_dividend", "summary": {"rows": 1000},
                "source_complete": True,
            }),
            "security_lifecycle_snapshot.json": json.dumps({
                "source": "dim_stock", "summary": {"rows": 5000},
                "source_complete": True,
            }),
        }
        evidence_dir = self._make_minimal_evidence_dir(tmp_path, **overrides)

        # Add valid data to root
        dates = list(pd.date_range("2025-01-02", "2025-06-30", freq="B"))
        nav_vals = np.cumprod(1 + np.random.randn(len(dates)) * 0.01)
        nav = pd.DataFrame({
            "trade_date": dates,
            "nav": nav_vals,
            "cash": nav_vals * 0.3,           # PR20: required column
            "market_value": nav_vals * 0.7,    # PR20: required column
            "accrued_cost": 0.0,               # PR20: required column
        })
        nav.to_parquet(evidence_dir / "daily_nav.parquet")
        # PR20: Write to per-experiment directories (covers 2025H1 window)
        for exp_id in ["P0", "C0", "A7", "A8", "A9"]:
            nav.to_parquet((evidence_dir / exp_id) / "daily_nav.parquet")

        candidates = pd.DataFrame({
            "trade_date": np.repeat(dates[:30], 5),
            "symbol": [f"{i:06d}" for i in range(150)],
            "rank_score": np.random.uniform(60, 100, 150),
        })
        candidates.to_parquet(evidence_dir / "daily_candidates.parquet")

        weights = candidates.copy()
        weights["final_portfolio_weight"] = 0.14
        weights.to_parquet(evidence_dir / "daily_weights.parquet")

        ledger = pd.DataFrame({
            "trade_date": dates[:20],
            "symbol": [f"{i:06d}" for i in range(20)],
        })
        ledger.to_parquet(evidence_dir / "trade_ledger.parquet")

        pd.DataFrame({
            "seed_id": [f"seed_{i}" for i in range(20)],
            "total_return": np.random.randn(20) * 0.1,
            "sharpe_ratio": np.random.randn(20) * 0.5 + 0.5,
        }).to_csv(evidence_dir / "random_seed_results.csv", index=False)

        report = validate_evidence_semantics(evidence_dir)
        assert report.passed, f"Should pass: {report.errors}"
        assert report.status == SemanticEvidenceStatus.REPRODUCIBLE.value

    def test_missing_random_results_fails(self, tmp_path):
        """Random seed file with only names (no returns) should fail."""
        from scripts.research.evidence_semantic import validate_evidence_semantics

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)
        # random_seed_results has only seed_id column from _make_minimal_evidence_dir

        report = validate_evidence_semantics(evidence_dir)
        assert not report.passed
        # Should detect missing return data
        random_check = report.checks.get("random_seeds", {})
        assert not random_check.get("passed", True)

    def test_precheck_detected(self, tmp_path):
        """Precheck package should be detected as PRECHECK_ONLY."""
        from scripts.research.evidence_semantic import is_precheck_only

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)
        # factor states say NOT_FITTED with precheck reason

        is_precheck, reason = is_precheck_only(evidence_dir)
        assert is_precheck
        assert "PRECHECK_ONLY" in reason

    def test_precheck_not_confused_with_reproducible(self, tmp_path):
        """PRECHECK_ONLY packages must not be classified as REPRODUCIBLE."""
        from scripts.research.validation_evidence import validate_evidence_package, EvidenceStatus

        evidence_dir = self._make_minimal_evidence_dir(tmp_path)

        # Add all required files with valid SHAs to pass structural check
        # But keep NOT_FITTED to trigger precheck

        result = validate_evidence_package(evidence_dir, run_semantic=True)
        assert not result["passed"]
        semantic = result.get("semantic", {})
        assert semantic.get("status") == EvidenceStatus.PRECHECK_ONLY.value


# ============================================================================
# L2: Golden Regression Smoke Test (no DB)
# ============================================================================


class TestGoldenRegressionSmoke:
    """Smoke test for golden regression without database."""

    def test_regime_coverage_check(self):
        """Verify regime coverage checker works."""
        from scripts.research.run_pr18_golden_regression import _check_regime_coverage

        # Create dates covering all required regimes
        dates = (
            list(pd.date_range("2024-01-02", "2024-06-28", freq="B"))
            + list(pd.date_range("2025-07-01", "2025-12-31", freq="B"))
            + list(pd.date_range("2026-01-02", "2026-06-30", freq="B"))
        )

        result = _check_regime_coverage(dates)
        assert result["passed"]
        assert result["total_dates"] >= 180

    def test_regime_coverage_insufficient(self):
        """Verify regime checker detects insufficient coverage."""
        from scripts.research.run_pr18_golden_regression import _check_regime_coverage

        # Only 2026 dates — missing 2024 and 2025H2
        dates = list(pd.date_range("2026-01-02", "2026-06-30", freq="B"))

        result = _check_regime_coverage(dates)
        assert not result["passed"]
        assert result["regimes"]["2024_weak"]["n_dates"] < 20

    def test_min_sessions_enforced(self):
        """Golden regression should enforce minimum 180 sessions."""
        from scripts.research.run_pr18_golden_regression import MIN_SESSIONS

        assert MIN_SESSIONS >= 180


# ============================================================================
# L3: Anti-Leakage Mutation Tests
# ============================================================================


class TestAntiLeakageMutation:
    """Future-data leakage detection via mutation testing."""

    def test_pit_slicing_respected(self):
        """Transform should only access data up to signal_date."""
        from scripts.research.alpha_estimator import AlphaEstimator, FittedAlphaState

        estimator = AlphaEstimator()
        state = FittedAlphaState(
            factor_weights={"relative_strength": 0.3, "trend_persistence": 0.2},
            factor_signs={"relative_strength": 1, "trend_persistence": 1},
            train_start="2026-01-02",
            train_end="2026-03-31",
            n_train_days=60,
        )

        # Create proper price data with trade_date column
        dates_a = list(pd.date_range("2026-01-02", periods=10, freq="B"))
        dates_b = list(pd.date_range("2026-01-02", periods=10, freq="B"))
        prices = pd.DataFrame({
            "symbol": ["A"] * 10 + ["B"] * 10,
            "trade_date": dates_a + dates_b,
            "adj_close": (
                list(np.cumprod(1 + np.random.randn(10) * 0.02))
                + list(np.cumprod(1 + np.random.randn(10) * 0.02))
            ),
        })

        # Create scores with trade_date for the signal date
        scores = pd.DataFrame({
            "symbol": ["A", "B"],
            "trade_date": [pd.Timestamp("2026-01-10")] * 2,
            "score": [80.0, 75.0],
            "opt_score": [6.0, 5.0],
            "claude_score": [70.0, 65.0],
        })

        # Signal date is mid-range
        signal_date = "2026-01-10"
        result = estimator.transform(state, signal_date, scores, prices)

        # Result should only contain rows for the signal date
        if not result.empty:
            result_dates = pd.to_datetime(result["trade_date"]).dt.date.unique()
            assert all(d <= pd.Timestamp(signal_date).date() for d in result_dates), (
                "transform() returned data after signal_date — future data leakage!"
            )

    def test_frozen_weights_not_modified(self):
        """FittedAlphaState should be immutable as a frozen dataclass."""
        from scripts.research.alpha_estimator import FittedAlphaState
        from dataclasses import FrozenInstanceError

        original_weights = {"relative_strength": 0.3, "trend_persistence": 0.2}
        state = FittedAlphaState(
            factor_weights=dict(original_weights),
            factor_signs={"relative_strength": 1, "trend_persistence": 1},
            train_start="2026-01-02",
            train_end="2026-03-31",
        )

        # Verify immutability of the dataclass field itself
        with pytest.raises(FrozenInstanceError):
            state.factor_weights = {"new_factor": 0.99}  # frozen dataclass


# ============================================================================
# L1: Invariant Tests
# ============================================================================


class TestInvariants:
    """Property-based invariant tests."""

    def test_oracle_decision_immutability(self):
        """FrozenDailyDecision should be immutable."""
        from scripts.research.frozen_oracle import FrozenDailyDecision

        decision = FrozenDailyDecision(
            signal_date="2026-01-02",
            symbols=("A", "B"),
            rank_scores=(95.0, 90.0),
            final_weights=(0.35, 0.35),
            total_exposure=0.70,
        )

        with pytest.raises(Exception):
            decision.symbols = ("X", "Y")  # frozen dataclass

    def test_weights_sum_to_exposure(self):
        """Constrained weight allocation should not exceed target exposure."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        # Use varied industries so caps don't prevent allocation
        raw = np.array([0.25, 0.22, 0.20, 0.18, 0.15])
        symbols = [f"S{i}" for i in range(5)]
        industries = ["A", "B", "C", "D", "E"]  # all different
        risk = np.array([0.25, 0.22, 0.20, 0.18, 0.15])

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            risk_values=risk,
            single_cap=0.20,
            industry_cap=0.25,
            top2_risk_cap=0.55,
            target_gross_exposure=0.70,
        )

        total = result["final_portfolio_weight"].sum()
        assert total <= 0.70 + 1e-6, f"Exposure exceeds target: {total:.6f} > 0.70"
        # Cash should be positive
        assert result["cash_weight"].iloc[0] >= 0.0

    def test_single_stock_cap_enforced(self):
        """No single stock should exceed single_cap."""
        from scripts.research.constrained_weights import constrained_weight_allocation

        raw = np.array([0.50, 0.30, 0.10, 0.05, 0.05])
        symbols = ["S1", "S2", "S3", "S4", "S5"]
        industries = ["A", "B", "C", "D", "E"]

        result = constrained_weight_allocation(
            raw_weights=raw,
            symbols=symbols,
            industries=industries,
            single_cap=0.15,
            target_gross_exposure=0.70,
        )

        assert (result["final_portfolio_weight"] <= 0.15 + 1e-6).all(), (
            f"Single stock cap violated: max={result['final_portfolio_weight'].max():.4f}"
        )


# ============================================================================
# PR16 Adapter Modification Independence Test
# ============================================================================


class TestAdapterIndependenceRegression:
    """Verify that modifying adapter output causes golden regression to fail.

    This is the key independence test: if we change the adapter's scoring
    logic, the oracle comparison MUST detect it and fail.
    """

    def test_modified_rank_scores_cause_diff(self):
        """Changing rank scores should cause candidate/weight diff."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B", "C", "D", "E"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                ),
            },
        )

        # Modified output — different rank scores
        modified_output = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["A", "B", "C", "D", "E"],
                "rank_score": [99.0, 88.0, 77.0, 66.0, 55.0],  # MODIFIED
                "final_portfolio_weight": [0.18, 0.16, 0.14, 0.12, 0.10],
            }),
        }

        result = compare_against_oracle(
            oracle, modified_output, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        # Should detect the rank score difference
        assert result.rank_score_diff_max > 0 or result.candidate_diff_max > 0 or not result.passed, (
            f"Expected rank_score_diff > 0, got {result.rank_score_diff_max}"
        )

    def test_modified_exposure_causes_diff(self):
        """Changing total exposure should be detected."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState,
            FrozenDailyDecision,
            OracleProvenance,
            OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B", "C", "D", "E"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                ),
            },
        )

        # Modified output — different exposure (simulating different target_exposure)
        modified_output = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["A", "B", "C", "D", "E"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.22, 0.19, 0.17, 0.14, 0.13],  # sums to 0.85
            }),
        }

        result = compare_against_oracle(
            oracle, modified_output, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert result.exposure_diff_max > 0.01


# ============================================================================
# Integration: validate_evidence_package with semantics
# ============================================================================


class TestIntegratedEvidenceValidation:
    """Integration tests for validate_evidence_package with semantic checks."""

    def test_structural_only_mode(self, tmp_path):
        """Without semantic checks, structural-only validation should work."""
        from scripts.research.validation_evidence import validate_evidence_package

        evidence_dir = tmp_path / "evidence"
        evidence_dir.mkdir()

        # Minimal structural-only valid manifest
        manifest = {
            "git_commit_sha": "abc",
            "worktree_clean": True,
            "config_sha": "sha1",
            "data_sha": "sha2",
            "calendar_sha": "sha3",
            "corporate_action_sha": "sha4",
            "lifecycle_sha": "sha5",
            "python_version": "3.11",
            "dependency_lock_sha": "sha6",
            "evidence_status": "PRECHECK_ONLY",
            "promotion_status": "PROMOTION_BLOCKED",
            "files": {},
        }
        (evidence_dir / "manifest.json").write_text(json.dumps(manifest))

        # Create required evidence files
        for name in ["git_state.json", "config_snapshot.json", "data_snapshot.json",
                      "calendar_snapshot.json", "corporate_action_snapshot.json",
                      "security_lifecycle_snapshot.json", "fold_definitions.json",
                      "factor_state_by_fold.json"]:
            (evidence_dir / name).write_text("{}")

        for name in ["daily_candidates.parquet", "daily_weights.parquet",
                      "daily_exposure.parquet", "daily_nav.parquet",
                      "trade_ledger.parquet", "rejection_ledger.parquet"]:
            pd.DataFrame().to_parquet(evidence_dir / name)

        for name in ["random_seed_results.csv", "walk_forward_metrics.csv",
                      "stitched_oos_nav.csv", "test_log.txt"]:
            (evidence_dir / name).write_text("")

        # Update manifest with file SHAs
        from scripts.research.validation_evidence import sha256_file
        manifest["files"] = {
            name: sha256_file(evidence_dir / name)
            for name in os.listdir(evidence_dir)
            if (evidence_dir / name).is_file() and name != "manifest.json"
        }
        (evidence_dir / "manifest.json").write_text(json.dumps(manifest))

        # Run WITHOUT semantic checks
        result = validate_evidence_package(evidence_dir, run_semantic=False)
        # Should pass structural checks but flag in semantic if run
        assert "errors" in result
