"""PR19: Production-grade Oracle Coverage and Evidence Invariants Tests.

Covers:
  L0 — Oracle Independence (enhanced: hash-based + provenance validation)
  L1 — Coverage Invariants (date matching, regime coverage, exit coverage)
  L2 — Independent Golden Mutation (stock, rank, weight, exposure, exit)
  L3 — Ledger-NAV Conservation (true cash+MV-cost=NAV)
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from test.v4_evidence_fixture import write_v4_cartesian_evidence

PROJECT_ROOT = Path(__file__).resolve().parents[1]
import sys
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ============================================================================
# L0: Oracle Independence (Enhanced)
# ============================================================================


class TestOracleIndependenceEnhanced:
    """Enhanced independence detection with hash-based checks."""

    def test_adapter_generated_oracle_fails(self):
        """Oracle generated by ProductionStrategyAdapter must fail."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            validate_oracle_provenance,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="scripts.research.strategy_adapters.ProductionStrategyAdapter",
                generating_function="ProductionStrategyAdapter.rank",
                generator_file_sha="abc123",
                config_sha="cfg_sha",
                data_snapshot_sha="data_sha",
            ),
            decisions={
                "2026-01-02": None,  # minimal
            },
            n_dates=1,
            date_range=("2026-01-02", "2026-01-02"),
        )

        result = validate_oracle_provenance(oracle)
        assert not result["passed"]
        assert any("adapter class" in e.lower() for e in result["errors"])

    def test_same_file_sha_fails(self):
        """Oracle and runtime with same file SHA must fail independence check."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            check_oracle_independence,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
                generator_file_sha="same_sha_12345",
                config_sha="cfg123",
                data_snapshot_sha="data123",
            ),
        )

        result = check_oracle_independence(
            oracle,
            runtime_class_name="FrozenAlphaRuntime",
            runtime_file_sha="same_sha_12345",  # SAME!
            runtime_git_sha="def456",
        )
        assert not result["is_independent"]
        assert result["is_self_referential"]
        assert any("same" in e.lower() and "file" in e.lower() for e in result["errors"])

    def test_tampered_class_but_matching_hash_fails(self):
        """Tampered generating_class but matching generator_file_sha still fails."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            check_oracle_independence,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.production.engine",  # looks innocent
                generating_function="export_daily_decisions",       # looks innocent
                generator_file_sha="real_sha_matches_runtime",
                config_sha="cfg123",
                data_snapshot_sha="data123",
            ),
        )

        result = check_oracle_independence(
            oracle,
            runtime_class_name="FrozenAlphaRuntime",
            runtime_file_sha="real_sha_matches_runtime",  # same file!
        )
        assert not result["is_independent"]
        assert any("same" in e.lower() for e in result["errors"])

    def test_missing_config_sha_fails_provenance(self):
        """File-based oracle missing config_sha must fail provenance validation."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            validate_oracle_provenance,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
                generator_file_sha="gen_sha",
                # config_sha is MISSING
                data_snapshot_sha="data_sha",
            ),
            decisions={"2026-01-02": None},
            n_dates=1,
            date_range=("2026-01-02", "2026-01-02"),
        )

        result = validate_oracle_provenance(oracle)
        assert not result["passed"]
        assert any("config_sha" in e.lower() for e in result["errors"])

    def test_approved_oracle_does_not_override_self_referential(self):
        """Approved oracle with approval_sha must NOT override independence errors.

        PR20: Approval documents known bias but does NOT make self-referential
        data independent. Adapter-generated oracles always fail independence
        regardless of approval signatures.
        """
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            check_oracle_independence,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="scripts.research.strategy_adapters.ProductionStrategyAdapter",
                generating_function="ProductionStrategyAdapter.rank",
                generator_file_sha="some_sha",
                config_sha="cfg123",
                data_snapshot_sha="data123",
                approved_by="chenyiyun",
                approval_sha="approved_record_sha_12345",
            ),
        )

        result = check_oracle_independence(
            oracle,
            runtime_class_name="FrozenAlphaRuntime",
        )
        # PR20: Approval must NOT override self-referential detection.
        # An adapter-generated oracle is self-referential regardless of approval.
        assert not result["is_independent"], (
            f"Approved adapter oracle must NOT be marked independent: {result}"
        )
        assert result["is_self_referential"], (
            f"Approved adapter oracle must still be self-referential: {result}"
        )
        # Approval should be noted as a warning, not a clearing of errors
        approval_warnings = [w for w in result.get("warnings", []) if "approved" in w.lower()]
        assert len(approval_warnings) > 0, (
            f"Approval should generate a warning annotation: {result.get('warnings', [])}"
        )


# ============================================================================
# L1: Coverage Invariants
# ============================================================================


class TestCoverageInvariants:
    """PR19: Hard coverage gates."""

    def test_missing_one_day_oracle_fails(self):
        """Missing one day in oracle must fail comparison."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, FrozenDailyDecision,
            OracleProvenance, OracleSource,
            compare_against_oracle,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
                generator_file_sha="gen_sha",
                config_sha="cfg_sha",
                data_snapshot_sha="data_sha",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("A", "B"),
                    rank_scores=(95.0, 90.0),
                    final_weights=(0.35, 0.35),
                    total_exposure=0.70,
                ),
                # Note: 2026-01-03 is MISSING
            },
            n_dates=1,
            date_range=("2026-01-02", "2026-01-02"),
        )

        runtime_outputs = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["A", "B"],
                "rank_score": [95.0, 90.0],
                "final_portfolio_weight": [0.35, 0.35],
            }),
            "2026-01-03": pd.DataFrame({  # Not in oracle
                "symbol": ["C", "D"],
                "rank_score": [85.0, 80.0],
                "final_portfolio_weight": [0.35, 0.35],
            }),
        }

        result = compare_against_oracle(
            oracle, runtime_outputs, top_n=2,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed, "Missing oracle date must cause FAIL"
        assert result.n_dates_missing_oracle > 0

    def test_extra_day_oracle_fails_date_coverage(self):
        """Oracle having extra dates not in runtime should fail date coverage."""
        from scripts.research.run_pr19_golden_regression import check_oracle_date_coverage
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
        )

        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={"2026-01-02": None, "2026-01-03": None, "2026-01-04": None},
            n_dates=3,
            date_range=("2026-01-02", "2026-01-04"),
        )

        check = check_oracle_date_coverage(
            oracle, {"2026-01-02", "2026-01-03"}, "P0"
        )
        assert not check["passed"]
        assert check["n_extra"] > 0

    def test_regime_coverage_insufficient_fails(self):
        """Missing market regime windows must fail."""
        from scripts.research.run_pr19_golden_regression import check_regime_coverage_hard

        # Only 2026Q1 dates — missing 2024 and 2025
        dates = list(pd.date_range("2026-01-02", "2026-03-31", freq="B"))
        result = check_regime_coverage_hard(dates)
        assert not result["passed"]
        assert result["windows"]["2024Q1"]["n_dates"] < 15

    def test_p0_exists_c0_missing(self):
        """P0 oracle present but C0 oracle missing should fail validation."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, OracleProvenance, OracleSource,
            validate_oracle_provenance,
        )

        # P0 is valid
        p0 = FrozenOracleState(
            strategy_id="P0_test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
                generator_file_sha="gen_sha",
                config_sha="cfg_sha",
                data_snapshot_sha="data_sha",
            ),
            decisions={"2026-01-02": None},
            n_dates=1,
            date_range=("2026-01-02", "2026-01-02"),
        )

        # C0 is empty
        c0 = FrozenOracleState(
            strategy_id="C0_test",
            experiment_id="C0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
            ),
            decisions={},
            n_dates=0,
            date_range=("", ""),
        )

        p0_ok = validate_oracle_provenance(p0)["passed"]
        c0_ok = validate_oracle_provenance(c0)["passed"]
        assert p0_ok, "P0 should pass provenance"
        assert not c0_ok, "C0 with zero dates should fail provenance"


# ============================================================================
# L2: Independent Golden Mutation
# ============================================================================


class TestGoldenMutation:
    """Mutation testing: every atomic change must cause golden failure."""

    def _make_baseline(self):
        """Create baseline oracle and matching runtime output."""
        from scripts.research.frozen_oracle import (
            FrozenOracleState, FrozenDailyDecision,
            OracleProvenance, OracleSource,
        )
        oracle = FrozenOracleState(
            strategy_id="test",
            experiment_id="P0",
            provenance=OracleProvenance(
                source=OracleSource.FROZEN_PRODUCTION_FILE,
                generated_at="2026-01-01T00:00:00",
                git_commit_sha="abc123",
                generating_class="independent.process",
                generating_function="independent.run",
                generator_file_sha="gen_sha",
                config_sha="cfg_sha",
                data_snapshot_sha="data_sha",
            ),
            decisions={
                "2026-01-02": FrozenDailyDecision(
                    signal_date="2026-01-02",
                    symbols=("000001", "000002", "000003", "000004", "000005"),
                    rank_scores=(95.0, 90.0, 85.0, 80.0, 75.0),
                    final_weights=(0.18, 0.16, 0.14, 0.12, 0.10),
                    total_exposure=0.70,
                    exit_decisions=(
                        {"symbol": "000001", "exit_date": "2026-01-02",
                         "exit_reason": "TIME_STOP", "exit_shares": "1000"},
                    ),
                ),
            },
            n_dates=1,
            date_range=("2026-01-02", "2026-01-02"),
        )

        runtime_outputs = {
            "2026-01-02": pd.DataFrame({
                "symbol": ["000001", "000002", "000003", "000004", "000005"],
                "rank_score": [95.0, 90.0, 85.0, 80.0, 75.0],
                "final_portfolio_weight": [0.18, 0.16, 0.14, 0.12, 0.10],
                "exit_symbol": ["000001", None, None, None, None],
                "exit_date": ["2026-01-02", None, None, None, None],
                "exit_reason": ["TIME_STOP", None, None, None, None],
                "exit_shares": ["1000", None, None, None, None],
            }),
        }

        return oracle, runtime_outputs

    def test_baseline_passes(self):
        """Baseline should pass golden regression."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        result = compare_against_oracle(
            oracle, runtime, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert result.passed, f"Baseline should pass: {result}"

    def test_mutate_one_symbol_fails(self):
        """Changing one stock symbol must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        # Mutate one symbol
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "symbol"] = "999999"
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed

    def test_mutate_one_rank_score_fails(self):
        """Changing one rank score must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "rank_score"] = 99.0  # was 95.0
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.rank_score_diff_max > 0

    def test_mutate_weight_1bp_fails(self):
        """Changing weight by 1bp (> tolerance) must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "final_portfolio_weight"] = 0.181  # was 0.18 (+1bp)
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.weight_diff_max > 0

    def test_mutate_exposure_1bp_fails(self):
        """Changing total exposure by > tolerance must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "final_portfolio_weight"] = 0.19  # was 0.18
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed

    def test_mutate_exit_date_fails(self):
        """Changing one exit date must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "exit_date"] = "2026-01-05"  # was 2026-01-02
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.exit_diff_count > 0

    def test_mutate_exit_reason_fails(self):
        """Changing one exit reason must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "exit_reason"] = "HARD_STOP"  # was TIME_STOP
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.exit_diff_count > 0

    def test_mutate_exit_shares_fails(self):
        """Changing one exit shares count must cause failure."""
        from scripts.research.frozen_oracle import compare_against_oracle

        oracle, runtime = self._make_baseline()
        mutated = runtime["2026-01-02"].copy()
        mutated.loc[0, "exit_shares"] = "500"  # was 1000
        runtime_mutated = {"2026-01-02": mutated}

        result = compare_against_oracle(
            oracle, runtime_mutated, top_n=5,
            test_class_name="FrozenAlphaRuntime",
        )
        assert not result.passed
        assert result.exit_diff_count > 0


# ============================================================================
# L3: Ledger-NAV Conservation
# ============================================================================


class TestLedgerNavConservation:
    """True ledger-NAV conservation: cash + market_value - costs = nav."""

    def test_conservation_passes_with_exact_match(self, tmp_path):
        """Exact conservation should pass."""
        from scripts.research.evidence_semantic import validate_ledger_nav_conservation

        nav_path = tmp_path / "nav.parquet"
        ledger_path = tmp_path / "ledger.parquet"

        pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=5, freq="B"),
            "nav": [1.0, 1.01, 0.99, 1.02, 1.03],
            "cash": [0.3, 0.31, 0.29, 0.32, 0.33],
            "market_value": [0.7, 0.7, 0.7, 0.7, 0.7],
            "accrued_cost": [0.0, 0.0, 0.0, 0.0, 0.0],
        }).to_parquet(nav_path)

        pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=3, freq="B"),
            "symbol": ["A", "B", "C"],
        }).to_parquet(ledger_path)

        result = validate_ledger_nav_conservation(nav_path, ledger_path, tolerance=0.0001)
        assert result["passed"], f"Exact conservation should pass: {result.get('errors')}"

    def test_cash_mutation_1_yuan_fails(self, tmp_path):
        """Mutating cash by 1 yuan must cause conservation failure."""
        from scripts.research.evidence_semantic import validate_ledger_nav_conservation

        nav_path = tmp_path / "nav.parquet"
        ledger_path = tmp_path / "ledger.parquet"

        nav = pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=5, freq="B"),
            "nav": [1.0, 1.01, 0.99, 1.02, 1.03],
            "cash": [0.3, 0.31, 0.29, 0.32, 0.33],
            "market_value": [0.7, 0.7, 0.7, 0.7, 0.7],
            "accrued_cost": [0.0, 0.0, 0.0, 0.0, 0.0],
        })
        nav.loc[0, "cash"] = 0.31  # was 0.30 → diff of 0.01
        # nav is still 1.0, but cash+mv = 0.31+0.70 = 1.01
        # This should trigger conservation violation (1bp = 0.0001 * 1.0 = 0.0001)
        nav.to_parquet(nav_path)

        pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=3, freq="B"),
            "symbol": ["A", "B", "C"],
        }).to_parquet(ledger_path)

        result = validate_ledger_nav_conservation(nav_path, ledger_path, tolerance=0.0001)
        assert not result["passed"], (
            f"Cash mutation by 1 yuan should fail: {result.get('errors')}"
        )
        assert result["details"].get("conservation_violations", 0) > 0

    def test_holdings_mutation_100_shares_fails(self, tmp_path):
        """Mutating market value (100 shares) must cause conservation failure."""
        from scripts.research.evidence_semantic import validate_ledger_nav_conservation

        nav_path = tmp_path / "nav.parquet"
        ledger_path = tmp_path / "ledger.parquet"

        nav = pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=5, freq="B"),
            "nav": [1.0, 1.01, 0.99, 1.02, 1.03],
            "cash": [0.3, 0.31, 0.29, 0.32, 0.33],
            "market_value": [0.7, 0.7, 0.7, 0.7, 0.7],
            "accrued_cost": [0.0, 0.0, 0.0, 0.0, 0.0],
        })
        nav.loc[0, "market_value"] = 0.71  # was 0.70
        # cash(0.3) + mv(0.71) - cost(0) = 1.01 ≠ nav(1.0)
        nav.to_parquet(nav_path)

        pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=3, freq="B"),
            "symbol": ["A", "B", "C"],
        }).to_parquet(ledger_path)

        result = validate_ledger_nav_conservation(nav_path, ledger_path, tolerance=0.0001)
        assert not result["passed"], (
            f"Market value mutation should fail: {result.get('errors')}"
        )

    def test_nonnegative_nav_enforced(self, tmp_path):
        """Negative NAV must be detected."""
        from scripts.research.evidence_semantic import validate_ledger_nav_conservation

        nav_path = tmp_path / "nav.parquet"
        ledger_path = tmp_path / "ledger.parquet"

        nav = pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=3, freq="B"),
            "nav": [-0.5, 1.01, 0.99],
            "cash": [0.3, 0.31, 0.29],
            "market_value": [0.7, 0.7, 0.7],
            "accrued_cost": [0.0, 0.0, 0.0],
        })
        nav.to_parquet(nav_path)

        pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=2, freq="B"),
            "symbol": ["A", "B"],
        }).to_parquet(ledger_path)

        result = validate_ledger_nav_conservation(nav_path, ledger_path, tolerance=0.0001)
        assert not result["passed"]
        assert any("negative" in e.lower() for e in result["errors"])


# ============================================================================
# L1 (continued): Per-Experiment×Window Evidence
# ============================================================================


class TestPerExperimentWindowEvidence:
    """PR19: Per-experiment×per-window evidence validation."""

    def test_per_experiment_structure_validates(self, tmp_path):
        """Evidence in per-experiment directories should be validated."""
        from scripts.research.evidence_semantic import validate_evidence_per_experiment_window

        evidence_dir = tmp_path / "evidence"
        evidence_dir.mkdir()

        # Create P0 subdirectory with data
        p0_dir = evidence_dir / "P0"
        p0_dir.mkdir()
        nav = pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=60, freq="B"),
            "nav": np.cumprod(1 + np.random.randn(60) * 0.01),
        })
        nav.to_parquet(p0_dir / "daily_nav.parquet")

        # Create A7 subdirectory with data
        a7_dir = evidence_dir / "A7"
        a7_dir.mkdir()
        nav_a7 = pd.DataFrame({
            "trade_date": pd.date_range("2026-01-02", periods=30, freq="B"),
            "nav": np.cumprod(1 + np.random.randn(30) * 0.01),
        })
        nav_a7.to_parquet(a7_dir / "daily_nav.parquet")

        # Missing A8, A9
        result = validate_evidence_per_experiment_window(evidence_dir)
        assert result["structure"] == "per_experiment"
        assert not result["passed"], "Missing A8/A9 directories should fail"
        assert "A8" in str(result["missing"])
        assert "A9" in str(result["missing"])

    def test_all_experiments_present_passes(self, tmp_path):
        """All V4 experiments with all ten quarters should pass."""
        from scripts.research.evidence_semantic import validate_evidence_per_experiment_window

        evidence_dir = tmp_path / "evidence"
        evidence_dir.mkdir()

        write_v4_cartesian_evidence(evidence_dir)

        result = validate_evidence_per_experiment_window(evidence_dir)
        assert result["structure"] == "per_experiment"
        assert result["passed"], (
            f"All experiments present should pass: {result.get('errors')}"
        )


# ============================================================================
# DB Exception Fail-Closed
# ============================================================================


class TestDBExceptionFailClosed:
    """PR19: DB exceptions must propagate, not silently return empty."""

    def test_load_from_db_raises_on_failure(self):
        """DB query failure must raise RuntimeError, not silently return empty."""
        from scripts.research.frozen_oracle import load_frozen_oracle_from_db
        from unittest.mock import MagicMock

        # Mock engine that raises on execute
        mock_engine = MagicMock()
        mock_engine.connect.side_effect = Exception("Connection refused")

        with pytest.raises(RuntimeError, match="Oracle DB query FAILED"):
            load_frozen_oracle_from_db(
                mock_engine, "test_strategy",
                "2026-01-01", "2026-06-30",
            )


# ============================================================================
# PR19 Golden Regression Smoke Test
# ============================================================================


class TestPR19GoldenRegressionSmoke:
    """Smoke tests for PR19 golden regression without database."""

    def test_regime_coverage_hard_all_passes(self):
        """Full coverage across all windows must pass."""
        from scripts.research.run_pr19_golden_regression import check_regime_coverage_hard

        dates = (
            list(pd.date_range("2024-01-02", "2024-06-28", freq="B"))
            + list(pd.date_range("2024-07-01", "2024-12-31", freq="B"))
            + list(pd.date_range("2025-01-02", "2025-06-30", freq="B"))
            + list(pd.date_range("2025-07-01", "2025-12-31", freq="B"))
            + list(pd.date_range("2026-01-02", "2026-06-30", freq="B"))
        )
        result = check_regime_coverage_hard(dates)
        assert result["passed"]
        assert result["total_dates"] >= 180

    def test_regime_coverage_hard_fails_short(self):
        """Only one window must fail hard."""
        from scripts.research.run_pr19_golden_regression import check_regime_coverage_hard

        dates = list(pd.date_range("2026-01-02", "2026-06-30", freq="B"))
        result = check_regime_coverage_hard(dates)
        assert not result["passed"]
        assert len(result["failures"]) > 1  # multiple windows missing + total

    def test_date_ranges_explicit(self):
        """Verify REQUIRED_DATE_RANGES covers all required periods."""
        from scripts.research.run_pr19_golden_regression import (
            REQUIRED_DATE_RANGES, MIN_SESSIONS_PER_WINDOW, MIN_TOTAL_SESSIONS,
        )
        assert len(REQUIRED_DATE_RANGES) == 10
        assert MIN_SESSIONS_PER_WINDOW >= 15
        assert MIN_TOTAL_SESSIONS >= 180

    def test_no_adapter_fallback(self):
        """PR19 runner must require explicit oracle paths."""
        from scripts.research.run_pr19_golden_regression import run_golden_regression
        import inspect

        # Verify the function signature requires oracles
        sig = inspect.signature(run_golden_regression)
        params = list(sig.parameters.keys())
        assert "p0_oracle_path" in params
        assert "c0_oracle_path" in params
