"""Frozen evidence contract for Full Strategy V3 validation runs."""

from __future__ import annotations

import hashlib
import json
from enum import Enum
from pathlib import Path
from typing import Any, Iterable

import pandas as pd


FIXED_WINDOWS = (
    ("2024Q1", "2024-01-01", "2024-03-31"),
    ("2024Q2", "2024-04-01", "2024-06-30"),
    ("2024Q3", "2024-07-01", "2024-09-30"),
    ("2024Q4", "2024-10-01", "2024-12-31"),
    ("2025Q1", "2025-01-01", "2025-03-31"),
    ("2025Q2", "2025-04-01", "2025-06-30"),
    ("2025Q3", "2025-07-01", "2025-09-30"),
    ("2025Q4", "2025-10-01", "2025-12-31"),
    ("2026Q1", "2026-01-01", "2026-03-31"),
    ("2026Q2", "2026-04-01", "2026-06-30"),
)

# PR20: Windows that are still in-progress as of the current date.
# These windows must NOT be used for promotion statistics.
INCOMPLETE_WINDOWS = frozenset({
    "2026Q3",  # In progress — ends 2026-09-30
    "2026Q4",  # In progress — ends 2026-12-31
})

# PR26A.9: manifest.json and evidence_verification.json are NOT in
# REQUIRED_EVIDENCE_FILES — they are generated by the finalization process
# and cannot be required before they exist.  Including them creates a
# circular dependency where manifest requires verification which requires
# manifest.
REQUIRED_EVIDENCE_FILES = frozenset({
    "git_state.json",
    "config_snapshot.json",
    "data_snapshot.json",
    "calendar_snapshot.json",
    "corporate_action_snapshot.json",
    "security_lifecycle_snapshot.json",
    "fold_definitions.json",
    "factor_state_by_fold.json",
    "walk_forward_metrics.csv",
    "test_log.txt",
    "manifest.json",
    "evidence_verification.json",
})

# PR26A.8: Evidence Contract V2 — per-strategy subdirectories.
# Each strategy directory must contain the listed files.  The manifest
# records SHA-256 hashes for every file in every directory, keyed by
# relative path (e.g. "P0/daily_nav.parquet").
REQUIRED_STRATEGY_DIRS: dict[str, frozenset[str]] = {
    "P0": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                      "daily_weights.parquet", "metrics.json"}),
    "C0": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                      "daily_weights.parquet", "metrics.json"}),
    "A7": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                      "daily_weights.parquet", "metrics.json"}),
    "A8": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                      "daily_weights.parquet", "metrics.json",
                      "a8_optimizer_ledger.parquet"}),
    "A9": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                      "daily_weights.parquet", "metrics.json"}),
    "REV_A7": frozenset({"daily_nav.parquet", "trade_ledger.parquet",
                          "daily_weights.parquet", "metrics.json"}),
    "RND_TOP30": frozenset({"random_seed_results.csv", "status.json"}),
    "RND_FULL": frozenset({"random_seed_results.csv", "status.json"}),
}

REQUIRED_MANIFEST_FIELDS = frozenset({
    "git_commit_sha",
    "worktree_clean",
    "config_sha",
    "data_sha",
    "calendar_sha",
    "corporate_action_sha",
    "lifecycle_sha",
    "python_version",
    "dependency_lock_sha",
    "evidence_status",
    "promotion_status",
    "files",
})


class EvidenceStatus(str, Enum):
    REPRODUCIBLE = "REPRODUCIBLE"
    NON_REPRODUCIBLE = "NON_REPRODUCIBLE"
    INSUFFICIENT_OOS_COVERAGE = "INSUFFICIENT_OOS_COVERAGE"
    PRECHECK_ONLY = "PRECHECK_ONLY"
    EMPTY_RESULTS = "EMPTY_RESULTS"


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def canonical_sha(payload: Any) -> str:
    return sha256_bytes(
        json.dumps(payload, ensure_ascii=False, sort_keys=True, default=str).encode()
    )


def build_fold_definitions(
    calendar_dates: Iterable[Any],
    score_dates: Iterable[Any],
    price_dates: Iterable[Any],
    embargo_days: int = 10,
    train_months: int = 24,
) -> list[dict[str, Any]]:
    calendar = sorted({pd.Timestamp(value).date() for value in calendar_dates})
    score_set = {pd.Timestamp(value).date() for value in score_dates}
    price_set = {pd.Timestamp(value).date() for value in price_dates}
    folds: list[dict[str, Any]] = []
    for label, window_start, window_end in FIXED_WINDOWS:
        start = pd.Timestamp(window_start).date()
        end = pd.Timestamp(window_end).date()
        validation_days = [day for day in calendar if start <= day <= end]
        if not validation_days:
            folds.append({
                "window": label,
                "status": EvidenceStatus.INSUFFICIENT_OOS_COVERAGE.value,
                "reason": "calendar_window_empty",
            })
            continue
        prior_days = [day for day in calendar if day < validation_days[0]]
        if len(prior_days) <= embargo_days:
            folds.append({
                "window": label,
                "status": EvidenceStatus.INSUFFICIENT_OOS_COVERAGE.value,
                "reason": "embargo_history_incomplete",
            })
            continue
        embargo = prior_days[-embargo_days:]
        train_end = prior_days[-embargo_days - 1]
        train_start = (pd.Timestamp(train_end) - pd.DateOffset(months=train_months)).date()
        train_days = [day for day in calendar if train_start <= day <= train_end]
        score_train = sum(day in score_set for day in train_days)
        score_validation = sum(day in score_set for day in validation_days)
        price_train = sum(day in price_set for day in train_days)
        price_validation = sum(day in price_set for day in validation_days)
        coverage = {
            "score_train": score_train / max(len(train_days), 1),
            "score_validation": score_validation / max(len(validation_days), 1),
            "price_train": price_train / max(len(train_days), 1),
            "price_validation": price_validation / max(len(validation_days), 1),
        }
        complete = bool(train_days) and all(value >= 0.999999 for value in coverage.values())
        folds.append({
            "window": label,
            "train_start": str(train_start),
            "train_end": str(train_end),
            "embargo_start": str(embargo[0]),
            "embargo_end": str(embargo[-1]),
            "validation_start": str(validation_days[0]),
            "validation_end": str(validation_days[-1]),
            "train_trading_days": len(train_days),
            "validation_trading_days": len(validation_days),
            "coverage": coverage,
            "status": (
                EvidenceStatus.REPRODUCIBLE.value
                if complete
                else EvidenceStatus.INSUFFICIENT_OOS_COVERAGE.value
            ),
            "reason": "" if complete else "required_score_or_price_dates_missing",
        })
    return folds


def overall_coverage_status(folds: list[dict[str, Any]]) -> EvidenceStatus:
    labels = {fold.get("window") for fold in folds}
    complete = (
        labels == {item[0] for item in FIXED_WINDOWS}
        and all(fold.get("status") == EvidenceStatus.REPRODUCIBLE.value for fold in folds)
    )
    return EvidenceStatus.REPRODUCIBLE if complete else EvidenceStatus.INSUFFICIENT_OOS_COVERAGE


def finalize_manifest(output_dir: Path, manifest: dict[str, Any]) -> dict[str, Any]:
    """PR26A.9 Evidence Contract V3 — validates root files AND per-strategy subdirectories.

    Returns the manifest dict with files/SHAs populated.  Does NOT write
    manifest.json — that is deferred to write_final_manifest() so the
    verification step can complete first without a circular dependency.
    """
    # Root-level files
    missing = sorted(REQUIRED_EVIDENCE_FILES - {path.name for path in output_dir.iterdir() if path.is_file()})
    if missing:
        manifest["evidence_status"] = EvidenceStatus.NON_REPRODUCIBLE.value
        manifest["promotion_status"] = "PROMOTION_BLOCKED"
        manifest["missing_files"] = missing
    manifest["files"] = {}
    for name in sorted(REQUIRED_EVIDENCE_FILES):
        fpath = output_dir / name
        if fpath.is_file():
            manifest["files"][name] = sha256_file(fpath)

    # PR26A.10: RND experiments that need recursive quarter-level hashing
    _RND_QUARTER_DIRS = frozenset({"RND_TOP30", "RND_FULL"})

    # Strategy subdirectories
    for dir_name, required_files in sorted(REQUIRED_STRATEGY_DIRS.items()):
        strat_dir = output_dir / dir_name
        if not strat_dir.is_dir():
            manifest.setdefault("missing_strategy_dirs", []).append(dir_name)
            continue
        # PR26A.10: For RND experiments, recursively hash quarter subdirectories
        if dir_name in _RND_QUARTER_DIRS:
            for fpath in sorted(strat_dir.rglob("*")):
                if fpath.is_file():
                    rel_path = str(fpath.relative_to(output_dir))
                    manifest["files"][rel_path] = sha256_file(fpath)
                    # Also add the flat path for backward compat with
                    # REQUIRED_STRATEGY_DIRS checks
                    flat_rel = f"{dir_name}/{fpath.name}"
                    if flat_rel not in manifest["files"]:
                        manifest["files"][flat_rel] = sha256_file(fpath)
            # Also check the flat required files exist
            for fname in sorted(required_files):
                fpath = strat_dir / fname
                if not fpath.is_file():
                    manifest.setdefault("missing_strategy_files", []).append(
                        f"{dir_name}/{fname}"
                    )
        else:
            for fname in sorted(required_files):
                fpath = strat_dir / fname
                rel_path = f"{dir_name}/{fname}"
                if fpath.is_file():
                    manifest["files"][rel_path] = sha256_file(fpath)
                else:
                    manifest.setdefault("missing_strategy_files", []).append(rel_path)

    if manifest.get("missing_strategy_dirs") or manifest.get("missing_strategy_files"):
        manifest["evidence_status"] = EvidenceStatus.NON_REPRODUCIBLE.value
        manifest["promotion_status"] = "PROMOTION_BLOCKED"

    # PR26A.9: Do NOT write manifest.json here — caller must call
    # write_final_manifest() after verification completes.
    return manifest


def write_final_manifest(
    output_dir: Path,
    manifest: dict[str, Any],
    verification_path: Path | None = None,
) -> Path:
    """PR26A.10 Evidence Contract V4: Write the final manifest.json ONCE at end.

    This must be the LAST step in the evidence finalization pipeline:
      1. Generate immutable evidence files
      2. Build manifest payload in memory (finalize_manifest)
      3. Run semantic + structural validation (against in-memory manifest)
      4. Write evidence_verification.json
      5. Compute SHA256 of evidence_verification.json file itself
      6. Call write_final_manifest() ONCE to write manifest.json

    The manifest itself is NOT re-hashed after writing — it records SHAs of
    all other evidence files but does not record its own SHA (which would be
    a circular dependency).

    If verification_path is provided, the manifest records
    verification_file_sha = sha256_file(verification_path) so the actual
    evidence_verification.json file on disk is bound to the manifest.
    Tampering with the verification file after finalization is detectable.
    """
    if verification_path is not None and verification_path.is_file():
        manifest["verification_file_sha"] = sha256_file(verification_path)
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    return manifest_path


def validate_evidence_package(
    output_dir: Path,
    run_semantic: bool = True,
    manifest_dict: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Validate an evidence package for structural and semantic integrity.

    Parameters
    ----------
    output_dir: Path to the evidence package directory.
    run_semantic: If True, also run semantic validation (content-level checks).
                  Set to False for pre-flight/precheck packages.
    manifest_dict: Optional pre-built manifest dict.  When provided, this is
                   used instead of reading manifest.json from disk.  This
                   enables the acyclic finalization flow where manifest.json
                   is only written once at the very end.

    Returns
    -------
    dict with: passed, errors, manifest, semantic (if run_semantic=True)
    """
    if manifest_dict is not None:
        manifest = manifest_dict
    else:
        manifest_path = output_dir / "manifest.json"
        if not manifest_path.is_file():
            return {"passed": False, "errors": ["manifest_missing"]}
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    errors: list[str] = []
    for field in sorted(REQUIRED_MANIFEST_FIELDS):
        if field not in manifest or manifest[field] in (None, ""):
            errors.append(f"manifest_field_missing:{field}")
    # Root-level evidence files
    for name in sorted(REQUIRED_EVIDENCE_FILES):
        path = output_dir / name
        if not path.is_file():
            errors.append(f"evidence_file_missing:{name}")
            continue
        expected = manifest.get("files", {}).get(name)
        # PR26A.9: missing SHA is a hard failure — not a silent pass
        if expected is None:
            errors.append(f"evidence_sha_missing:{name}")
        elif expected != sha256_file(path):
            errors.append(f"evidence_sha_mismatch:{name}")
    # PR26A.8: Per-strategy subdirectory validation
    for dir_name, required_files in sorted(REQUIRED_STRATEGY_DIRS.items()):
        strat_dir = output_dir / dir_name
        if not strat_dir.is_dir():
            errors.append(f"strategy_dir_missing:{dir_name}")
            continue
        for fname in sorted(required_files):
            fpath = strat_dir / fname
            rel_path = f"{dir_name}/{fname}"
            if not fpath.is_file():
                errors.append(f"strategy_file_missing:{rel_path}")
                continue
            expected = manifest.get("files", {}).get(rel_path)
            # PR26A.9: missing SHA is a hard failure — not a silent pass
            if expected is None:
                errors.append(f"strategy_sha_missing:{rel_path}")
            elif expected != sha256_file(fpath):
                errors.append(f"strategy_sha_mismatch:{rel_path}")
    # PR26A.10: verification_file_sha — bind evidence_verification.json to manifest
    verification_path = output_dir / "evidence_verification.json"
    verif_file_sha = manifest.get("verification_file_sha")
    if verif_file_sha is not None:
        if not verification_path.is_file():
            errors.append("verification_file_missing:evidence_verification.json")
        elif verif_file_sha != sha256_file(verification_path):
            errors.append("verification_file_sha_mismatch:evidence_verification.json may have been tampered")
    if manifest.get("worktree_clean") is not True:
        errors.append("worktree_not_clean_at_run_start")

    structural_passed = not errors

    # Semantic validation (content-level checks)
    semantic_result: dict[str, Any] | None = None
    if run_semantic:
        from scripts.research.evidence_semantic import (
            validate_evidence_semantics,
            is_precheck_only,
            SemanticEvidenceStatus,
        )
        # Check if this is a precheck package first
        is_precheck, precheck_reason = is_precheck_only(output_dir)
        if is_precheck:
            semantic_result = {
                "passed": False,
                "status": SemanticEvidenceStatus.PRECHECK_ONLY.value,
                "reason": precheck_reason,
            }
            errors.append(f"semantic:PRECHECK_ONLY:{precheck_reason}")
        else:
            report = validate_evidence_semantics(output_dir)
            semantic_result = {
                "passed": report.passed,
                "status": report.status,
                "checks": {k: v.get("passed", False) for k, v in report.checks.items()},
                "errors": report.errors,
                "warnings": report.warnings,
            }
            for err in report.errors:
                errors.append(f"semantic:{err}")

    return {
        "passed": structural_passed and (semantic_result.get("passed", True) if semantic_result else True),
        "errors": errors,
        "manifest": manifest,
        "semantic": semantic_result,
    }


def validate_evidence_package_from_dict(
    output_dir: Path,
    manifest: dict[str, Any],
    run_semantic: bool = True,
) -> dict[str, Any]:
    """PR26A.10: Validate evidence using an in-memory manifest dict.

    This is the preferred entry point for the acyclic finalization flow.
    The caller builds the manifest in memory, runs validation against it,
    writes evidence_verification.json, then calls write_final_manifest()
    ONCE at the end.  manifest.json is never read during this flow, so
    the order is truly acyclic.
    """
    return validate_evidence_package(output_dir, run_semantic=run_semantic, manifest_dict=manifest)
